# Generated by Django 4.2.3 on 2023-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0003_alter_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.TextField(blank=True),
        ),
    ]
