# Generated by Django 4.2.6 on 2023-11-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0006_rename_hobby_student_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Hobby',
        ),
    ]
