# Generated by Django 4.2.3 on 2023-10-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Emailid', models.EmailField(max_length=254)),
                ('JoiningDate', models.DateField()),
                ('Qualification', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=255)),
            ],
        ),
    ]
