# Generated by Django 4.2.3 on 2023-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0002_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.CharField(max_length=255),
        ),
    ]
