# Generated by Django 4.2.6 on 2023-11-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0004_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobby',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
