# Generated by Django 4.2.6 on 2023-11-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0005_student_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='hobby',
            new_name='Hobby',
        ),
    ]
